name = "BizBasic"
license = "MIT"
licenselink = "https://github.com/berkaycubuk/bizbasic-hugo/blob/master/LICENSE"
description = "BizBasic is a Hugo theme built with TailwindCSS. It’s not revolutiniary but simple and responsive."
homepage = "https://bizmovo.com/product/bizbasic-hugo-theme/"
tags = ["landing page", "simple", "tailwind"]
features = ["tailwind", "simple"]
min_version = "0.112.3"

[author]
  name = "Berkay Çubuk"
  homepage = "https://berkaycubuk.com"
